export const LOADING='LOADING'
export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const REGISTER_FAILED='REGISTER_FAILED'

export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAILED='LOGIN_FAILED'

export const GET_USER_SUCCESS='GET_USER_SUCCESS'
export const GET_USER_FAILED='GET_USER_FAILED'
export const LOGOUT='LOGOUT'