export const PROD_LOADING='PROD_LOADING'
// get all products
export const GET_ALL_PRODUCTS_SUCCESS='GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAILED='GET_ALL_PRODUCTS_FAILED'
// get prod byId

export const PROD_DETAILS_SUCCESS='PROD_DETAILS_SUCCESS'
export const PROD_DETAILS_FAILED='PROD_DETAILS_FAILED'
//add prod
export const ADD_PRODUCT_SUCCESS='ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILED='ADD_PRODUCT_FAILED'

//edit product
export const EDIT_PRODUCT_SUCCESS='EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_FAILED='EDIT_PRODUCT_FAILED'
//delet product
export const DELET_PRODUCT_SUCCESS='DELET_PRODUCT_SUCCESS'
export const DELET_PRODUCT_FAILED='DELET_PRODUCT_FAILED'